services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ".env"
    volumes:
      - ".:/opt/downloader"
  db:
    image: mongo:7.0.8
    volumes:
      - db_data:/data/db

volumes:
  db_data:
